name: Process HTML and Deploy

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  process_files:
    runs-on: ubuntu-latest  # 指定运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Remove JavaScript files
      run: find . -type f -name '*.js' -delete  # 删除所有.js文件

    # - name: Replace text in HTML files
    #   run: |
    #     find . -maxdepth 1 -type f -name '*.html' -exec sed -i 's|<img src="./|<img src="https://page.jituc.cn/juejin/Node + React 实战：从 0 到 1 实现记账本/|g' {} +
    # 在一级目录下的HTML文件中替换指定文本

    - name: Generate index.html
      run: |
        echo "<html><body><ul>" > index.html
        for file in *.html; do
          echo "<li><a href='https://bairihai.github.io/Juejin-visResumeMook/$file'>$file</a></li>" >> index.html
        done
        echo "</ul></body></html>" >> index.html

    - name: Create and push to a new branch
      run: |
        git config --global user.name 'bairihai'
        git config --global user.email '237876867@qq.com'
        git checkout -b gh-pages
        git add .
        git commit -m "Automated changes by GitHub Actions"
        git push -f https://${{ secrets.GH_BRH_REPO_TOKEN }}@github.com/bairihai/Juejin-visResumeMook.git HEAD
      # 提交更改并强制推送到新的分支
      # 需要先修改仓库里的github action权限
      # git checkout -b deploy-branch-$(date +%Y%m%d-%H%M)  # 原本是创建以日期和时间命名的新分支，最后可能分支太多，不太好管理，所以就专用一个分支了

    # - name: Deploy to Server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     port: ${{ secrets.PORT }}
    #     source: "."
    #     target: "/path/on/server"
    # 使用 SCP 将文件部署到服务器